import '../../../styles/Footer.css'
import '../../../styles/Header.css'
import '../../../styles/Diseases.css'
import '../../../styles/index.css'
import '../../../styles/haveAQuestion.css'
import '../../../styles/treatment_algorithms.css'
